### ISSUE TITLE
Noise Gate doing nothing

### ISSUE THREAD

**Issue by tfki** [brummer10/guitarix#103]
running 0.43.1 the noise gate knob has no effect whatsoever. confirmed this with a friend of mine.

**Comment by brummer10** [comment]
Ups, yes, thanks for reporting. I've fixed that now in the git repository.

**Comment by tfki** [comment]
just rebuilt the project and it still does not work for me. The button right next to the dial is pressed and the dial is turned up to max, still, almost inaudible noise is not filtered.

**Comment by tfki** [comment]
still does not seem to work. i manually changed the factor with which fnglevel is multiplied to 1 and it started to work. the behavior is still not as expected though. quiet noises get filtered properly but just as any sound above the gate starts, there is an audible 'crack' sound.

**Comment by brummer10** [comment]
You should better use the abgate (under the misc tab) then, it will give you more control over the behaviour of the gate.
